#!/bin/bash
# Export current WordPress content to seed-content.sh
# Run from project root: bash wordpress/export-content.sh

WP="docker exec aiaiai-wordpress wp --allow-root"
SEED_FILE="$(dirname "$0")/seed-content.sh"

echo "=== Exporting WordPress content to seed-content.sh ==="

cat > "$SEED_FILE" << 'HEADER'
#!/bin/bash
# Seed WordPress pages with AIAIAI content
# Auto-generated by export-content.sh — DO NOT EDIT MANUALLY
# Run inside WordPress container: bash /tmp/seed-content.sh

WP="wp --allow-root"

echo "=== Seeding AIAIAI WordPress Content ==="

$WP rewrite structure '/%postname%/' 2>/dev/null
$WP rewrite flush 2>/dev/null

# Only seed if page has no content yet
seed_if_empty() {
  local PAGE_ID=$1
  local DATA=$2
  EXISTING=$($WP post meta get $PAGE_ID page_sections 2>/dev/null)
  if [ -z "$EXISTING" ] || [ "$EXISTING" = "" ] || [ "$EXISTING" = "null" ] || [ "$EXISTING" = "{}" ]; then
    $WP post meta update $PAGE_ID page_sections "$DATA"
    return 0
  else
    echo "  (skipped — already has content)"
    return 1
  fi
}

HEADER

for slug in home about services partner humanoid security; do
  # Get page title
  TITLE=$($WP post list --post_type=page --name=$slug --field=post_title 2>/dev/null)
  if [ -z "$TITLE" ]; then
    case $slug in
      home) TITLE="Home" ;;
      about) TITLE="About Us" ;;
      services) TITLE="Services" ;;
      partner) TITLE="AI Solution Partner" ;;
      humanoid) TITLE="AI-Enhanced Humanoid Robotics" ;;
      security) TITLE="AI Security Guard Solution" ;;
    esac
  fi

  # Get current content
  DATA=$($WP post meta get $($WP post list --post_type=page --name=$slug --field=ID 2>/dev/null) page_sections 2>/dev/null)

  if [ -z "$DATA" ] || [ "$DATA" = "" ]; then
    echo "Skipping $slug — no content"
    continue
  fi

  # Escape single quotes for bash heredoc
  SLUG_UPPER=$(echo "$slug" | tr '[:lower:]' '[:upper:]')

  cat >> "$SEED_FILE" << PAGEEOF
###############################################################################
# ${SLUG_UPPER} PAGE
###############################################################################
${SLUG_UPPER}_ID=\$(\$WP post list --post_type=page --name=${slug} --field=ID 2>/dev/null)
if [ -z "\$${SLUG_UPPER}_ID" ]; then
  ${SLUG_UPPER}_ID=\$(\$WP post create --post_type=page --post_title='${TITLE}' --post_name='${slug}' --post_status='publish' --porcelain)
fi

seed_if_empty \$${SLUG_UPPER}_ID '$(echo "$DATA" | sed "s/'/'\\\\''/g")'
echo "✓ ${TITLE} (ID: \$${SLUG_UPPER}_ID)"

PAGEEOF

  echo "Exported: $slug ($TITLE)"
done

cat >> "$SEED_FILE" << 'FOOTER'

echo ""
echo "=== Seeding complete ==="
FOOTER

chmod +x "$SEED_FILE"
echo ""
echo "=== Done! seed-content.sh updated ==="
